### ISSUE TITLE
notify.js

### ISSUE THREAD

**Issue by dkanada** [MechDex/MechDex#2]
possible notification library, requires jquery but looks super simple

**Comment by kalenpw** [comment]
How much are you wanting to use this? It does look really simple, but I started working on an alert system and it doesn't seem to hard

**Comment by kalenpw** [comment]
And it jQuery-less :^)

**Comment by dkanada** [comment]
Go for it, this was just in case we needed to throw something in at the end or if notifications turned out to be hard.
